#--------------------------------------------------------------
#          Makefile for molecular_dynamics module
#--------------------------------------------------------------

# List module object filenames
molecular_dynamics_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/molecular_dynamics/,$(molecular_dynamics_objects))
