#--------------------------------------------------------------
#          Makefile for moleculardynamics module
#--------------------------------------------------------------

# List module object filenames
moleculardynamics_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/moleculardynamics/,$(moleculardynamics_objects))
